import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { NuqsAdapter } from "nuqs/adapters/next/app";
import 'antd/dist/reset.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NuqsAdapter>
          <AntdRegistry>{children}</AntdRegistry>
        </NuqsAdapter>
      </body>
    </html>
  );
}
